### ISSUE TITLE
Content Wrap-up

### ISSUE THREAD

**Issue by evidens** [christinatruong/llc-intro-to-python#4]
Here's the content of Christina's Email with checkmarks so we can tick them off when they're done.

- [x] slide12 - should we add a note that every time your enter a command in the console it runs it? Also, discovered in PyCharm ( and probably others ) if you do Shift + Enter you can add a line break without running the command.  Maybe we should just mention this verbally and add a note later since it’s crunch time!
- [x] slide 13 needs link to data types resource @dmilliken 
- [x] slide 18 second typecasting example, no solution for converting numbers to strings.  @dmilliken 
- [x] slide 27 add explanation for `...` in console.
- [x] slide 28 - changed the weather example back as a class exercise to give them exercise with the syntax.  Then after comparison operators, and/or - added a weather part 2 exercise for them to go back and update it to use temp values and operators. Though this might be the best way to solve the "how much should we make them do on their own" problem.  Thoughts?
- [x] slide41 - Really needs to be split into an explanation of importing libraries before the nuts & bolts of using the `DictReader`

**Comment by evidens** [comment]
@christinatruong Re: Slide 12 hmm, I thought running through the console exercises people would pick up on that. It feels like we're maybe adding a lot of side commentary that detracts from the main content?
I've never actually used the shift + enter thing since you typically run one line at a time (or in the case of nested structures it will give you the `...` for continuation).

**Comment by evidens** [comment]
@christinatruong I revised the indentation slide and put it after the exercise (since I wanted to show them the success case before the error). I added a note about paying attention to white space and figure the instructor or mentors can fill in as needed.

**Comment by christinatruong** [comment]
Re: Slide 12 - was thinking it was good to add a side note in case they forget when they go home and try it again and try to copy and paste the whole thing.  I don't think we need to add the Shift + Enter after all.  too much extra info. But we can just leave it the way it is with the "Also note the ... symbols. don't type it" comment. No need to add any more explanation than that.  Just a reminder.

**Comment by christinatruong** [comment]
@evidens Will be adding this to the LLC repo after we're done.  Usually we have no instructor info to make it easier to share but since you're the first one teaching it, why don't you update that as well!

**Comment by evidens** [comment]
Hmm, I briefly saw more stuff in the description and then as I clicked to tick off slide 28 it went away again. Not sure if I over-wrote someone's items :s

**Comment by christinatruong** [comment]
Meh. I'm sure it's fine :)  Looks like all items ticked. I'm going to do one more quick run through!

**Comment by dmilliken** [comment]
Looking good!

**Comment by dmilliken** [comment]
Who is responsible for fixing the csv library slides?

**Comment by evidens** [comment]
I'm working on that right now

**Comment by christinatruong** [comment]
Just ran through it, it looks great!  Love the gifs :+1: 
I just commented out the wifi/instructor info - @evidens you can add that later and present your version of the slides if you want.  Also commented out the "lunchtime" slide so you can take a break whenever there's a natural break around 12:30pm.  Just take note of what slide works best as a lunch time break and we'll add it in officially after!

**Comment by evidens** [comment]
Okay, sounds good!
I'm just finishing up the import explanation and then we should be ready to go!

**Comment by christinatruong** [comment]
Oh! Can someone look over the learner email? Maybe @dmilliken? Second page: https://docs.google.com/document/d/1HCG7ZbL0ArdiRR0UKe-rMoH5Ccsz7X7dqJ01fZVeXMc/edit#

**Comment by dmilliken** [comment]
Learner email looks good!
On windows I think they may want to change one of the default install options to set the path, but it's not needed to do the workshop. Not sure if it's worth including but it is unique to windows.

**Comment by christinatruong** [comment]
@dmilliken eh... next workshop.  Those who have problems can just come early! 
@evidens we good to go with the slides?

**Comment by dmilliken** [comment]
Nevermind, you can only set the path through the installer in Python 3. Carry on!

**Comment by evidens** [comment]
@christinatruong Yes! We're good to go! (well, good enough for now. MVP, right?)

**Comment by dmilliken** [comment]
![Angels](http://31.media.tumblr.com/94aba62c26b3ec8b96c667386eb737c3/tumblr_miiqceoMxo1s410g9o1_500.gif)

**Comment by christinatruong** [comment]
Yes MVP :)  I'm going to fork this repo from the LLC account so any future issues, revisions etc, we'll do it from there.  YAY! We did it!

**Comment by evidens** [comment]
Sweet! I made a small change to the email so it says "python --version" (otherwise they might be dumped into a console and wonder how to get out).

**Comment by evidens** [comment]
@dmilliken :+1: on the gifs :)

**Comment by christinatruong** [comment]
ok on the email.

**Comment by dmilliken** [comment]
Thanks @evidens :D
I was hoping for more diversity, though. Next time!

**Comment by christinatruong** [comment]
Email is scheduled to go out in 30mins (in case I forget something!) and new repo here: 
https://github.com/ladieslearningcode/llc-intro-to-python

I haven't added you two as collaborators on that but we can also just keep using this repo for changes after the workshop and then just do one big pull request!  Thanks so much!!!! Now go rest :)
