### ISSUE TITLE
Updates following the first run-through

### ISSUE THREAD

**Issue by evidens** [christinatruong/llc-intro-to-python#5]
- [x] slide 9 – the note about which browser to use isn't terribly relevant to the Python workshop (except for the slides) @knowcliu 
- [ ] slide 14 – add float and other types for consistency with int an str
- [x] slide 14 – show proper True, False (not lower case) @knowcliu
- [ ] slide 14 – remove mention of list type
- [ ] new slide after 14 – explain that variable names are arbitrary so people don't ascribe too much meaning to them
- [ ] new slide before 15 – briefly describe functions/methods in so far as we'll be using them in the course
- [ ] slide 30 – show that boolean conditions joined with `and` need to have the variable stated twice: i.e. `x > 0 and x < 5` not like in math where you'd state 0 < x < 5
- [ ] slide 38-9 – rework the explanation of `for` to show repeating instructions going into the indented block (consider graphics or similar)
- [ ] slide 40 – uncomment lunch slide, it seems to be at the right spot
- [x] slide 43 – fix file open path to match console @knowcliu
- [ ] new slide before 45 – re-iterate how `for` loops work on CSV data objects after lunch (people forget what they don't repeat)
- [ ] slide 46 - fix demo file to remove `../exercises` since it's unnecessary

**Comment by evidens** [comment]
@christinatruong is it possible to enable issues on the LLC master version of this so future work can be pull-requested directly to that repo?

**Comment by christinatruong** [comment]
@evidens For sure. Just enabled it!

**Comment by evidens** [comment]
Transferred to https://github.com/ladieslearningcode/llc-intro-to-python/issues/2
